name: Ping Backend Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  
  workflow_dispatch:  

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Backend Endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://dementia-diary-backend.onrender.com
